[build]
publish = "packages/gatsby-website/public"
package = "packages/gatsby-website"
command = "cd packages/gatsby-website && npm install && npm run build-prod"
# ignore changes to any other package
ignore = "git diff --name-only $CACHED_COMMIT_REF $COMMIT_REF | tr -d '\n' | grep -qv '^packages/gatsby-website/'"

[[redirects]]
  from = "https://omardelarosa.com/tags/*"
  to = "https://classic.omardelarosa.com/tags/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://omardelarosa.com/posts/*"
  to = "https://classic.omardelarosa.com/posts/:splat"
  status = 301
  force = true