[build]
publish = "packages/gatsby-website/public"
package = "packages/gatsby-website"
command = "cd packages/gatsby-website && npm install && npm run build-prod"

[[redirects]]
  from = "https://omardelarosa.com/tags/*"
  to = "https://classic.omardelarosa.com/tags/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://omardelarosa.com/posts/*"
  to = "https://classic.omardelarosa.com/posts/:splat"
  status = 301
  force = true