[build]
publish = "packages/obs-site"
package = "packages/obs-site"
command = "touch packages/obs-site/index.html && echo 'Hello, World!' > packages/obs-site/index.html"

[[redirects]]
  from = "https://omardelarosa.com/notes/*"
  to = "https://publish.obsidian.md/serve?url=omardelarosa.com/notes/:splat"
  status = 200
  force = true