[build]
publish = "packages/obs-site"
package = "packages/obs-site"
command = "echo 'noop build...'"

[[redirects]]
  from = "https://omardelarosa.com/*"
  to = "https://publish.obsidian.md/serve?url=omardelarosa.com/:splat"
  status = 200
  force = true