[build]
publish = "packages/obs-site"
package = "packages/obs-site"
command = "echo 'noop build...'"
# ignore changes to any other package
ignore = "git diff --name-only $CACHED_COMMIT_REF $COMMIT_REF | tr -d '\n' | grep -qv '^packages/obs-site/'"

[[redirects]]
  from = "https://omardelarosa.com/notes/*"
  to = "https://publish.obsidian.md/serve?url=omardelarosa.com/notes/:splat"
  status = 200
  force = true