[build]
publish = "packages/obs-site/"
package = "packages/obs-site"
command = "touch index.html && echo 'Hello, World!' > index.html"

[[redirects]]
  from = "https://obsidian.omardelarosa.com/*"
  to = "https://publish.obsidian.md/serve?url=obsidian.omardelarosa.com/:splat"
  status = 200
  force = true