[build]
publish = "packages/obs-static-site/dist"
command = "cd packages/obs-static-site && npm install && npm run build"

[[redirects]]
  from = "https://omardelarosa.com/*"
  to = "https://classic.omardelarosa.com/projects"
  status = 301
  force = true

[[redirects]]
  from = "https://omardelarosa.com/*"
  to = "https://publish.obsidian.md/serve?url=omardelarosa.com/:splat"
  status = 200
  force = true